### ISSUE TITLE
Can you please add a practical example how this is supposed to work? Where is the exploration stack, is this to be started in an active canvas etc

### ISSUE THREAD

**Issue by torstenkoepke** [hjamet/Canvas-Explorer#2]

**Comment by gleyconJ** [comment]
"Please, I also didn't understand how it works."
Help us!

**Comment by ksdavidc** [comment]
had this problem at first, but now I get it. The reason is that it is a bit primitive and could use a better interface.

what happens is:

1. pick a file from which to start.
2. run the command "ajouter note" (this means "add note" in french)
3. the program will search this file for linked notes, and in binary tree fashion will run through the linked notes, one at a time, and the linked notes in the linked notes, until all the linked and sublinked notes are encountered.
4. At each juncture, in the current tab, the subsequent note to be reviewed will appear. 
5. You must choose either to "ajouter note" to include this note, or "ignorer note" (ignore the note). 
6. There will be a popup telling you how many notes are left to review.
7. When you have up and down the tree to all the nodes, a new popup will ask you to give a name to the canvas it will create.
8. The canvas appears in the current tab.

- While I like the concept, I think it would be easier and faster to review if one could see an overview of what was going on. For example a sidebar with a list of notes that are in the tree and the number included/excludes, and checkboxes one can use for inclusion/exclusion and a button to press when you are done at any point. This would be much more effective and less time consuming, and provide better real time feedback as to what is happening. I could think of further additions at that point (adding new notes to the tree, so that the tree could have several initial nodes, for example)

- Not being able to stop the process midway does not seem to be implemented, other than by just moving on to other files/tabs.

**Comment by hjamet** [comment]
Hello !

I apologize a thousand times over for not getting back to you sooner and thank https://github.com/ksdavidc from the bottom of my heart for doing so! This plugin was originally a simple personal project: I wasn't thinking of publishing it, but now that I've seen that other people are interested in it, I'm definitely going to try to improve it to make it clearer and easier to use!
